### ISSUE TITLE
breaks with multiple connections

### ISSUE THREAD

**Issue by AlJohri** [gvalkov/wtee#1]
I get `OSError: fd 0 already registered` when I open two tabs in my browser both at `localhost:8080`.

The command I ran was:

```
tail -f /var/log/system.log | wtee | nl
```

I'm on Mac OS X El Capitan 10.11.6 using Python 3.5.

```
Traceback (most recent call last):
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/tornado/websocket.py", line 412, in _run_callback
    callback(*args, **kwargs)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/sockjs/tornado/transports/websocket.py", line 41, in open
    self.session.verify_state()
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/sockjs/tornado/session.py", line 301, in verify_state
    super(Session, self).verify_state()
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/sockjs/tornado/session.py", line 112, in verify_state
    self.conn.on_open(self.conn_info)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/wtee/server.py", line 58, in on_open
    io_loop.add_handler(self.stdin_buffer, self.on_stdin, io_loop.READ)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 725, in add_handler
    self._impl.register(fd, events | self.ERROR)
  File "/Users/johria/anaconda3/lib/python3.5/site-packages/tornado/platform/kqueue.py", line 40, in register
    raise IOError("fd %s already registered" % fd)
OSError: fd 0 already registered
```

**Comment by gvalkov** [comment]
Fixed in 1c08399c4b8a6a201f95074813cfd1b607d2f2d4. I'll push out a new release later today. Thanks!
