### ISSUE TITLE
wtee error in ubuntu16.04

### ISSUE THREAD

**Issue by cloudfirst** [gvalkov/wtee#2]
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

$ sudo pip list 
wtee (1.1.0)
sockjs-tornado (1.0.3)
tornado (5.0.1)

$ wtee
Traceback (most recent call last):
  File "/usr/local/bin/wtee", line 11, in <module>
    load_entry_point('wtee==1.1.0', 'console_scripts', 'wtee')()
  File "/usr/local/lib/python2.7/dist-packages/wtee/main.py", line 141, in main
    application = server.WTeeApplication(config, client_config, template_dir, assets_dir)
  File "/usr/local/lib/python2.7/dist-packages/wtee/server.py", line 138, in __init__
    routes, self.ws_handler = self.setup_routes()
  File "/usr/local/lib/python2.7/dist-packages/wtee/server.py", line 120, in setup_routes
    ws_handler = sockjs.tornado.SockJSRouter(WebsocketWTee, os.path.join('/', self.relative_root, 'ws'))
  File "/usr/local/lib/python2.7/dist-packages/sockjs/tornado/router.py", line 111, in __init__
    self.io_loop)
TypeError: __init__() takes exactly 3 arguments (4 given)

**Comment by gvalkov** [comment]
Hi. This is related to an [issue](https://github.com/mrjoes/sockjs-tornado/pull/114) in `sockj-tornado`. I've released wtee 1.1.1, which pins tornado to <=5.0.0. Thanks for the catch.
